### ISSUE TITLE
[Navi21] test_conv_igemm_dynamic (Failed)

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1054]
ROCm 4.2, OCL backend, Navi21, Full test: `test_conv_igemm_dynamic (Failed)`.

`WORKAROUND_ISSUE_1054` is used to avoid this error.

**Comment by atamazov** [comment]
@junliume @JehandadKhan Can you please assign this?

**Comment by carlushuang** [comment]
Hi @atamazov please check https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1038#discussion_r676092147

**Comment by atamazov** [comment]
@carlushuang Would you like to tell that iGEMM dynamic kernels are not applicable for Navi21 and, therefore, the test should not be used? If yes, then this ticket is invalid. Please close it.

**Comment by carlushuang** [comment]
@atamazov yes. the assembly kernel is different for each architecture, or at least in ABI part. In this case, `test_conv_igemm_dynamic` only valid for vega.

**Comment by atamazov** [comment]
> @atamazov yes. the assembly kernel is different for each architecture, or at least in ABI part. In this case, `test_conv_igemm_dynamic` only valid for vega.

BTW we have some "universal" assembly kernels for a long time. The kernels employ conditional assembly and macros to achieve this.

**Comment by carlushuang** [comment]
Hi @atamazov yes, by using macros we can indeed reduce the number of kernels, with the sacrifice of becoming less human readable. We are thinking about this, because change from gfx9 to gfx10 is relatively large. I'm not sure if this can be achieved or not right now, but we are taking this into consideration in future kernel development.
Will update the old kernels if we found gfx10 kernels is indeed compatible (or with just small amount of macros) with gfx9.

**Comment by atamazov** [comment]
@carlushuang Please notice `inst_wrappers.inc` and `rocm_version.inc`. I recommend re-using these (or borrowing the approach) in your kernels if you decide to share kernel sources among different GPU architectures.
