### ISSUE TITLE
[Test][CI][gfx90a] Temporarily disabled unit tests

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1093]
[Target]
re-enable the list of tests which have been disabled temporarily on gfx90a platform:

- [x] test_conv2d 
- [x] test_find_db 
- [x] test_main 
- [x] test_immed_conv2d

[Cause]

1.  The first three is caused by *Assembly error*
2.  test_immed_conv2d is caused by:
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/jenkins_and_docker_file_for_90a/52/pipeline/ 
> [2021-08-17T22:53:54.837Z] MIOpen(HIP): Warning [ParseAndLoadDb] File is unreadable: /var/jenkins/workspace/_jenkins_and_docker_file_for_90a/src/kernels/gfx90a_xnack68.HIP.fdb.txt
> [2021-08-17T22:53:54.837Z] <instantiation>:65:5: error: .amdhsa_reserve_xnack_mask does not match target id
> [2021-08-17T22:53:54.837Z]     .amdhsa_reserve_xnack_mask               __sgpr_reserve_xnack_default

**Comment by shaojiewang** [comment]
As we need to open test_conv2d on gfx90a, this error is observed: 
For gfx90a arch, some asm kernels use .amdhsa_reserve_xnack_mask, it seems like to cause a compile error: ```.amdhsa_reserve_xnack_mask does not match target id```
CI is blocked: http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/asm_igemm_wrw_nhwc_gfx90a/9/pipeline/213/

**Comment by carlushuang** [comment]
`EPILOG_KERNEL_DESCRIPTOR miopenSp3AsmConv_v21_1_2_gfx9_fp32_stride1`
from the log of the CI, winograd kernel happens to be compiled, where the compiler complain about an unrecognized syntax. Maybe winograd need to be disabled on gfx90a test environment
cc @DrizztDoUrden

**Comment by JehandadKhan** [comment]
@Kirpich30000 can you please take a look at the Winograd kernel and suggest future steps for enablement on gfx90a.

**Comment by atamazov** [comment]
As far as I see, the root reason of all the issues is assembly errors. In order to fix these errors we need access to gfx90a or logs of faulty cases taken with level 6.

**Comment by Slimakanzer** [comment]
As far as I see, this problem is caused by running winograd on gfx90a with **_xnack on_**.
In the shader [metadata](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/kernels/Conv_Winograd_v21_1_2_metadata.inc#L133) it is explicitly defined that the **xnack** should be disabled, which led to assembly errors.
The _Winograd_v21_1_2_ kernel supports **_xnack on_**, but it can lead to significant performance losses.

However, on the gfx90a **_xnack_** can be enabled/disabled on the fly using the _HSA_XNACK_ environment variable, without restarting the system.
If **_xnack_** is disabled, then the winograd kernel launches without assembly errors and performance loss.

However, do all asm kernels that can currently be run on gfx90a support **_xnack=on_**? Not all, I suspect.

**Comment by atamazov** [comment]
## The root reasons of the issue
- XNACK mode is enabled by default on gfx90a
- No support for enabled XNACK in assembly shaders

### XNACK mode enabled by default on gfx90a

- Leads to substantial performance drop due to lower issue rate of MEM instructions in this mode even if replay does not happen
- It is unclear if this mode is really needed
- XNACK mode can be controlled dynamically.

### No support for enabled XNACK in assembly shaders

We did not waste time & efforts on this, since this mode is, in principle, slower. Also, AFAIK this mode is intended for use in APUs that are not designed for high performance computing (and not supported by the library).

### Action points

- [ ] :construction: Disable assembly shaders when XNACK is enabled (#1142)
- [ ] Revise all cases when some assembly Seolver is disabled specifically for gfx90a but enabled for other gfx9 parts. gfx90a is able to execute any gfx9 assembly shaders ( TODO in #1142)
- [ ] Discuss and decide on XNACK on gfx90a
  - [ ] What is the proper default mode (enabled or disabled)
  - [ ] Do we need to support high performance when/if it is enabled
  - [ ] Can we switch XNACK mode from within the library
  - [ ] Decide on further steps
    - [ ] Do we need to support XNACK=On in assembly shaders etc.

**Comment by atamazov** [comment]
Actions points at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1093#issuecomment-914674242 updated.

**Comment by atamazov** [comment]
Tests enabled.
