### ISSUE TITLE
[MI100][FP16] ConvHipImplicitGemmForwardV4R4Xdlops verification issue

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1189]
```
./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 --input 128 832 7 7 --weights 128 832 1 1 --batch_size 128 --input_channels 832 --output_channels 128 --spatial_dim_elements 7 7 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 2 2 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW 
FAILED: 0.0836643
Forward convolution: ConvHipImplicitGemmForwardV4R4Xdlops
```

**Comment by atamazov** [comment]
Let's verify this (develop + latest ROCm RC) and close if not reproducible.

**Comment by junliume** [comment]
[Issue_1189.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/7946553/Issue_1189.log)
Issue is not reproducible with the driver command; however, different algorithm is selected (ConvAsmImplicitGemmGTCDynamicFwdXdlops instead of ConvHipImplicitGemmForwardV4R4Xdlops)
Shall we force (if possible) the selected algorithm and try more diagnostics? @atamazov

**Comment by atamazov** [comment]
Of course. How: https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1188#issuecomment-945211219

**Comment by junliume** [comment]
@atamazov Err... how to interpret this result?
> root@gb-sjc2-19:/root/MIOpen/build# ./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 --input 128 832 7 7 --weights 128 832 1 1 --batch_size 128 --input_channels 832 --output_channels 128 --spatial_dim_elements 7 7 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 2 2 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW                                              

>root@gb-sjc2-19:/root/MIOpen/build# MIOPEN_FIND_MODE=normal MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvHipImplicitGemmForwardV4R4Xdlops ./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 --input 128 832 7 7 --weights 128 832 1 1 --batch_size 128 --input_channels 832 --output_channels 128 --spatial_dim_elements 7 7 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 2 2 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW

./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 --input 128 832 7 7 --weights 128 832 1 1 --batch_size 128 --input_channels 832 --output_channels 128 --spatial_dim_elements 7 7 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 2 2 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW
**FAILED: /root/MIOpen/src/ocl/convolutionocl.cpp:1212: Backward Data Convolution cannot be executed due to incorrect params**
Backward convolution: ConvHipImplicitGemmForwardV4R4Xdlops
Input tensor: 128, 832, 7, 7
Weights tensor: 128, 832, 1, 1
Output tensor: 128, 128, 7, 7
Filter: conv2d, miopenConvolution, miopenPaddingDefault, {0, 0}, {1, 1}, {2, 2},
./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 --input 128 832 7 7 --weights 128 832 1 1 --batch_size 128 --input_channels 832 --output_channels 128 --spatial_dim_elements 7 7 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 2 2 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW
**FAILED: /root/MIOpen/src/ocl/convolutionocl.cpp:1561: Backward Weights Convolution cannot be executed due to incorrect params**
Backward weights convolution: ConvHipImplicitGemmForwardV4R4Xdlops
Input tensor: 128, 832, 7, 7
Weights tensor: 128, 832, 1, 1
Output tensor: 128, 128, 7, 7
Filter: conv2d, miopenConvolution, miopenPaddingDefault, {0, 0}, {1, 1}, {2, 2},
