### ISSUE TITLE
[tests] `test_reduce_test --D 1024 30528` fails

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1410]
Leftover from #1409. This works:
```bash
$ ./bin/MIOpenDriver reduce -A 1 -B 0 -C 1 -D 1024,30528,1 -I 0 -N 1 -O 0 -R 0,1,2
ReduceTensor() Verifies on CPU and GPU (err=0.000094)
```
But this doesn't:
```bash
$ ./bin/test_reduce_test --scales 1 0 --CompType 1 --D 1024 30528 1 --I 0 --N 1 ---ReduceOp 0 --R 0 1 2 -v
FAILED: 0.0272532
Max diff: 851954
Mismatch at 0: 3.04087e+07 != 3.12606e+07
verify_reduce_no_indices failed
Input Tensor 1024, 30528, 1
```
The `--tolerance` option does not help.

As a result, this case was not added to the tests. **_The fix should include adding it._**

**Comment by qianfengz** [comment]
MIOpenDriver and test_reduce_test depend on different methods for initializing data.  Since test_reduce_test needs supports both batch testing and interactive testing, and its batch testing has all operations covered,  its data initializing is more complicated and it is hard for test_reduce_test to specify a suitable tolerance value for any unexpected testing case.    For example, MIOpenDriver initializes all input data be in the range of (0, 1), but when operation MUL is tested,    1024 * 30528 values in (0, 1) could lead to underflow/overflow when accumulated.   The target of test_reduce_test is to ensure the batch testing works well for various operation types and reduction situation using specific tensor case.

**Comment by qianfengz** [comment]
The above case can be solved by using a similar initializing data as MIOpenDriver uses and enlarge the tolerance for ADD from 80 to 800.  But do we really need to do so ?
