### ISSUE TITLE
[Tests][Navi21][fp16] added test_reduce_test from #1415 still fails with nan

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1423]
**[Keywords]:**
test; Navi21; reduction; fp16
**URGENCY :HIGH** since it is already in the develop branch

**[Env]:**
Navi21
ROCm 5.0
**FP16**

**[Description]:**
related to #1415 and https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1415#issuecomment-1036515269

It is failing the CI test and my local builds on gfx1030 **for FP16**.
Problematic CI: http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/develop/492/pipeline/
```
# ./bin/test_reduce_test --scales 1 0 --CompType 1 --D 1024 30528 1 --I 0 --N 1 ---ReduceOp 0 --R 0 1 2 -v
./bin/test_reduce_test --float --D 1024 30528 1 --R 0 1 2 --ReduceOp 0 --CompType 1 --N 0 --I 0 --scales 1 0 
error: 4.70829e-05
Max diff: 14.7188
Mismatch at 0: 312599 != 312614
verify_reduce_no_indices failed
Input Tensor 1024, 30528, 1
```
```
# ./bin/test_reduce_test --half --D 1024 30528 1 --R 0 1 2 --ReduceOp 0 --CompType 1 --N 0 --I 0 --scales 1 0 
./bin/test_reduce_test --half --D 1024 30528 1 --R 0 1 2 --ReduceOp 0 --CompType 1 --N 0 --I 0 --scales 1 0 
FAILED: -nan
Iteration: 0
verify_reduce_no_indices failed
Input Tensor 1024, 30528, 1
Max diff: nan
Mismatch at 0: inf != inf
Non finite number found in cpu at 0: inf
Non finite num

**Comment by junliume** [comment]
Do those large tensors make sense for FP16? `HALF_ENABLED` is applied here. @qianfengz

**Comment by qianfengz** [comment]
I think we could not guarantee the data we provided for testing will not cause overflowing for half_t when the tensor rank/extent is very special.   For this `--half` case, both the Host and Gpu reduction lead to overflow, and the same is true for using MIOpenDriver. Since we using a fixed method to set up data,  we could not guarantee our data is suitable for any Reduction testing case given by the user. 

If the customer has one testing case for ONNX-RT, they muse ensure the testing data (tensor rank/extent, element values) be reasonable.   Our testing (MIOpenDriver or test_reduce_test) can only guarantee cases already tested by ourselves be reasonable with our methods of setting up the data.

**Comment by qianfengz** [comment]
> Do those large tensors make sense for FP16? `HALF_ENABLED` is applied here. @qianfengz

Does not make sense for real application situation of FP16, since fp16 max is 65504, lowest is -65504. Assume the mean of data is `0.01`,  then the sum of `1024*30528` values could be approximately `3052800`, which will lead to overflow.

**Comment by qianfengz** [comment]
The issue can be solved by moving the mean value to 0.001 from 0.01 (needed to keep the result in scope for fp16) and move the max_value to 9999 from 999 (needed for reducing accumulative error for fp32). Like the following 
`max_value = miopen_type<T>{} == miopenHalf ? 13 : miopen_type<T>{} == miopenInt8 ? 127 : 9999;`
`sign_value * rand_value / max_value + 0.001`

And some change also need be made to let `MIOpenDriver reducefp16` pass that testing case since currently it uses positive values to initialize the data, which will have a mean of approximately  0.5

Do will really need all those change ?  Or just remove the testing case from CI for half_t ?

**Comment by junliume** [comment]
@qianfengz Thank you for your detailed explanations. Yes, I have removed the test case from CI but I removed it for all cases (half and float) on an urgent basis. I think we can add it back for float only.

**Comment by atamazov** [comment]
@junliume I recommend:
- Adding `add_custom_test(test_reduce_custom_float HALF_DISABLED...` with the only test case (`...--D 1024 30528...`)
- Removing `WORKAROUND_ISSUE_1423`
- And then closing this ticket

**Comment by atamazov** [comment]
@qianfengz wrt https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1423#issuecomment-1038904243 -- let's keep in mind your idea ;)

**Comment by junliume** [comment]
> @junliume I recommend:
> 
> * Adding `add_custom_test(test_reduce_custom_float HALF_DISABLED...` with the only test case (`...--D 1024 30528...`)
> * Removing `WORKAROUND_ISSUE_1423`
> * And then closing this ticket

Branch `fix_1423` was created a few days ago for that purpose. I wish to let it pass CI tests before making a PR :)
