### ISSUE TITLE
How to create and add operator into the fusion plan?

### ISSUE THREAD

**Issue by Delta0307** [ROCmSoftwarePlatform/MIOpen#1665]

**Comment by Delta0307** [comment]
I am learning to use the fusion API according to [Fusion API: Getting Started](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/Getting_Started_FusionAPI.html#create-and-add-operators). This is my sample code：
```cpp
#include <hip/hip_runtime.h>
#include <stdio.h>
#include <miopen.h>

int main()
{
    miopenHandle_t handle;
    miopenCreate(&handle);

    miopenFusionPlanDescriptor_t fusePlanDesc;
    miopenFusionDirection_t miopenVerticalFusion;
    miopenTensorDescriptor_t inputDesc;
    miopenCreateTensorDescriptor(&inputDesc);
    miopenCreateFusionPlan(&fusePlanDesc, miopenVerticalFusion, inputDesc);

    miopenFusionOpDescriptor_t convOp;
    miopenConvolutionDescriptor_t convDesc;
    miopenCreateConvolutionDescriptor(&convDesc);
    miopenTensorDescriptor_t weightDesc;
    miopenCreateTensorDescriptor(&weightDesc);
    miopenCreateOpConvForward(fusePlanDesc, &convOp, convDesc, weightDesc);

    miopenFusionOpDescriptor_t biasOp;
    miopenTensorDescriptor_t bDesc;
    miopenCreateTensorDescriptor(&bDesc);
    miopenCreateOpBiasForward(fusePlanDesc, &biasOp, bDesc);

    miopenFusionOpDescriptor_t activOp;
    miopenCreateOpActivationForward(fusePlanDesc, &activOp,    miopenActivationRELU);

    miopenDestroyFusionPlan(fusePlanDesc);
    miopenDestroy(handle);
    printf("success!\n");
    return 0;
}
```
When it comes to the 21st line（miopenCreateOpConvForward(fusePlanDesc, &convOp, convDesc, weightDesc);）, there is a runtime error: ```segmentation fault (core dumped)```. I don't know what I should do. There is the same runtime error when running [miopen examples](https://github.com/ROCmSoftwarePlatform/MIOpenExamples/blob/master/fusion/main.cpp). I guess there is a problem with the environment configuration.

**Comment by Yanxing-Shi** [comment]
Hi, @Delta0307 Thank you for your interest in MIOpen.
- First of all, I ran the [miopen examples](https://github.com/ROCmSoftwarePlatform/MIOpenExamples/blob/master/fusion/main.cpp) and didn't find segmentation fault as you mentioned.
- Second, I find that your sample code has problems because the shape of the real data is needed to create the plan and the Op of each plan, which corresponds to the shape of tensor descriptors `inputDesc`, `weightDesc`, and `bDesc` in your code. So you need to define the shape of these three tensor descriptors in order for it to work.

If you have any questions about MIOpen, please feel free to ask us. Thank you！
cc @junliume @carlushuang
