### ISSUE TITLE
CK installation via requirements.txt fails, but manual process works

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1783]
**[Symptoms]**:
CK installation failed via `requirements.txt`
```
ROCmSoftwarePlatform/composable_kernel@2c6d63d0317d1a765b4e9f9b85177bb51a373b88 -DCXX=/opt/rocm/llvm/bin/clang++ -DCMAKE_PREFIX_PATH=/opt/rocm -DCMAKE_CXX_FLAGS=" -O3 " -DAMDGPU_TARGETS="gfx900;gfx906;gfx908;gfx90a;gfx1030"
```
with
```
CMake Error at /usr/local/cget/build/tmp-02fbef70b750b6b77fb764cf01c3ba6b65f11b384b94325f0dbc82e0bc3c3903/build/_deps/googletest-src/googletest/cmake/internal_utils.cmake:192 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "Clang"

  version 15.0.0.
```

However, if manually enter the temporary directory
```
/usr/local/cget/build/tmp-02fbef70b750b6b77fb764cf01c3ba6b65f11b384b94325f0dbc82e0bc3c3903/
```
and then
```
cd /usr/local/cget/build/tmp-02fbef70b750b6b77fb764cf01c3ba6b65f11b384b94325f0dbc82e0bc3c3903/
rm -rf build/;mkdir build;cd build;
CXX=/opt/rocm/llvm/bin/clang++ cmake -DCMAKE_PREFIX_PATH=/opt/rocm -D CMAKE_CXX_FLAGS=" -O3 " -DAMDGPU_TARGETS="gfx900;gfx906;gfx908;gfx90a;gfx1030" ../composable_kernel-2c6d63d0317d1a765b4e9f9b85177bb51a373b88/
```
then everything works as expected.

**[Discussion]**:
Simple Steps to reproduce this issue:
```
alias ptdrun=' sync && sudo /sbin/sysctl vm.drop_caches=3 && sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --ipc=host --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v ~/dockerx:/dockerx -v /data:/data --shm-size=64G'

ptdrun rocm/miopen:ci_rocm530
```
then
```
export LC_ALL=C.UTF-8 && \
export LANG=C.UTF-8 && \
apt-get update -y && \
apt-get install -y sudo && \
sudo apt-get -y install git unzip python3-venv pkg-config && \
sudo apt update && \
cd /root && git clone -b ci_rocm530_ubuntu2204 https://github.com/ROCmSoftwarePlatform/MIOpen && cd MIOpen
```
then **remove all other inputs in requirements.txt to save time**:
**Keep the ONLY line in `requirements.txt`**
```
ROCmSoftwarePlatform/composable_kernel@2c6d63d0317d1a765b4e9f9b85177bb51a373b88 -DCXX=/opt/rocm/llvm/bin/clang++ -DCMAKE_PREFIX_PATH=/opt/rocm -DCMAKE_CXX_FLAGS=" -O3 " -DAMDGPU_TARGETS="gfx900;gfx906;gfx908;gfx90a;gfx1030"
```
then
```
cmake -P install_deps.cmake --minimum
```

@pfultz2 could you take a look at this issue? I suppose the two approaches should be identical unless `cget` has some special environment calling different cmake?

**[Workaround]**
As changed in `ci_rocm530_ubuntu2004`, the workaround is to install CK from Dockerfile

**Comment by pfultz2** [comment]
So cget uses a toolchain file under `$CGET_PREFIX/cget/cget.cmake` to set cmake variables, so it would invoke it with `cmake -DCMAKE_TOOLCHAIN_FILE=$CGET_PREFIX/cget/cget.cmake -DCMAKE_INSTALL_PREFIX=$CGET_PREFIX` plus any additional `-D` flags listed in the requirements.txt(see [here](https://cget.readthedocs.io/en/latest/src/building.html#installing-cmake-packages)). You can also run with `--verbose` flag with `cget` and it will show the commands its running plus run cmake with verbose.

This happens when building googletest through `FetchContent`. I dont know if `FetchContent` is doing something wrong. I would need to see the full log(ideally with `--verbose`).

There is a couple of problems I see though.

First passing `-DCXX` does not set the compiler. The compiler needs to be set by the toolchain(ie by [`cget init --cxx ...`](https://cget.readthedocs.io/en/latest/src/commands.html#cmdoption-init-cxx), `CMAKE_TOOLCHAIN_FILE`, using [`cxx`](https://radeonopencompute.github.io/rbuild/doc/html/config.html#envvar-cxx) in rbuild.ini or using `CXX` environment variable) and should not be set in the requirements.txt. This could cause problems.

Secondly, there is no reason to set `-DCMAKE_CXX_FLAGS=" -03 "`. Its already set when using `Release` build type. And this could cause problem when cmake does tests on the compiler as well(like what #1771 is fixing).

Thirdly, you should not use `-DCMAKE_PREFIX_PATH` in the requirements.txt. Cget will override this in the toolchain file. Composable kernels should be doing `list(APPEND CMAKE_PREFIX_PATH /opt/rocm)` like what we do in [MIOpen](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/CMakeLists.txt#L123), [MIGraphX](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/targets/gpu/CMakeLists.txt#L25), [rocBLAS](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/CMakeLists.txt#L108) and what is documented [here](https://rocmdocs.amd.com/en/latest/Installation_Guide/Using-CMake-with-AMD-ROCm.html#finding-dependencies).

**Comment by junliume** [comment]
Thanks @pfultz2 removing the `-DCXX=/opt/rocm/llvm/bin/clang++ ` part indeed has helped.
Adding the `--verbose` line does not seem to have any effects though.
