### ISSUE TITLE
How to install the miopenkernels-<arch> package

### ISSUE THREAD

**Issue by learner321** [ROCmSoftwarePlatform/MIOpen#186]
I found the kernels compiled time is too long for the first time running. But I don't find the  pre-complied kernel package in the repository of "http://repo.radeon.com/rocm/yum/rpm". Could you please share the download link or how to build that package. Thank you.

**Comment by aserio** [comment]
@JehandadKhan, would you be able to shed some light here?

**Comment by JehandadKhan** [comment]
@learner321 thanks for reaching out, the kernels packages are not released yet but should be out in a few weeks. I will update this issue when new information becomes available.

**Comment by learner321** [comment]
@JehandadKhan Thank you. Now the compiled kernels are storing in the ~/.cache for differnent users. I will compile the kernels again even the other users have been trained before ,like some common sizes for conv/pooling. Is there some mechanism to share the complied kernels like system-db.

**Comment by learner321** [comment]
I find that pre-complied kernels has been released in rocm3.5. After installed, I delete the miopen caches and config in the ~/.cache/miopen and ~/.config/miopen. I test some samples that can be found in the /opt/rocm-3.5.0/miopen/share/miopen/db/*.HIP.fdb.txt such as "64-56-56-1x1-128-56-56-32-0x0-1x1-1x1-0-NCHW-FP32-F", *.kdb also can be found in that dir.  however, after ran the test, kern_db and perf config still generated in the ~/.cache/miopen and ~/.config/miopen. Meanwhile, the kernel still complied in the first time and spend long time. Is there some special parameter need to be set? Thank you :)

**Comment by JehandadKhan** [comment]
@learner321 Due to size restrictions, not all configs found in *.fdb.txt files are shipped in kernel db, therefore, it is possible that even though an entry exists in the find-db it may not be shipped with a precompiled kernel.

The compile time parameter `MIOPEN_ENABLE_SQLITE_KERN_CACHE` may be used to control this feature, while running CMake. This feature is enabled by default in ROCm v3.5.0 ( MIOpen v 2.4.0), and therefore does not need to be enabled specifically.
