### ISSUE TITLE
Can miopen specify the convolution algorithm for miopenConvolutionForward? 

### ISSUE THREAD

**Issue by deltaguo** [ROCmSoftwarePlatform/MIOpen#1864]
Can miopen specify the convolution algorithm for miopenConvolutionForward? 
when I try ```algo = miopenConvolutionFwdAlgoGEMM;```, A runtime error  occured：
```shell
MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/data/driver/MLOpen/src/ocl/convolutionocl.cpp:635: No invoker was registered for convolution forward. Was find executed?
    Error occurred:
```

**Comment by atamazov** [comment]
@Delta0307 Yes, but how this should be done depends on which API you are using ([Find API or Immediate mode API](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/find_and_immediate.md)). Please let us know so we can provide more specific assistance.

**Comment by atamazov** [comment]
@Delta0307 **_I am assuming that you are using Find API._**

In this case you have to call `miopenConvolutionForwardGetWorkSpaceSize()` and `miopenFindConvolutionForwardAlgorithm()` prior invoking convolution. Then you have to check that the output of `miopenFindConvolutionForwardAlgorithm()` (an array of miopenConvAlgoPerf_t) contains GEMM algo. If there is no GEMM there, then GEMM kernel is not ready to run, and you'll get the error shown in the topmost comment.

Possible reasons:
- (1) GEMM algo is not applicable for the desired convolution.
- (2) GEMM algo is globally disabled (this can be done during library build or in the environment)
- (3) The library is operating in the one of the optimized [Find Modes](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/find_and_immediate.md#find-modes) and the library "knows" that the GEMM algorithm is not the fastest one. Explanation:
  - Optimized Find modes: FAST, HYBRID, DYNAMIC_HYBRID (the latter is the current default).
  - In these modes, MIOpen attempts to reuse the results of previous Find calls in order to optimize host-side performance (see [here](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/finddb.md) for more info).
  - When find-db contains necessary information, MIOpen builds/prepares _only the fastest_ kernel/algorithm during `miopenFindConvolutionForwardAlgorithm()`.
  - For the majority of convolutions, the above means that GEMM is not prepared for use, because it is rarely the fastest solution.

The most likely reason is (3).

What you can do:
- For reason (1) - nothing
- For reason (2) - enable GEMM algo
- For reason (3) - switch to the NORMAL Find mode. The library will always build all available algorithms during `miopenFindConvolutionForwardAlgorithm()`, so all the applicable algos (including GEMM) will be ready for use in `miopenConvolutionForward()`.
  - ⚠️ The cost is hosts-side overhead.

**Comment by deltaguo** [comment]
@atamazov Thanks for your answer, I am now able to specify the algorithm I want to use by using the Immediate mode API. But for these algorithms provided by MIOpen:
```cpp
typedef enum
{
    miopenConvolutionAlgoGEMM         = 0, /*!< GEMM variant */
    miopenConvolutionAlgoDirect       = 1, /*!< Direct convolutions */
    miopenConvolutionAlgoFFT          = 2, /*!< Fast Fourier Transform indirect convolutions */
    miopenConvolutionAlgoWinograd     = 3, /*!< Winograd indirect convolutions */
    miopenConvolutionAlgoImplicitGEMM = 5, /*!< Implicit GEMM convolutions */
} miopenConvAlgorithm_t;
```
What is the difference between **miopenConvolutionAlgoGEMM** and **miopenConvolutionAlgoImplicitGEMM**？
Are they im2col algorithms？

**Comment by atamazov** [comment]
@Delta0307 This is a bit out of scope of the discussions in this repo. In short, the order of computations is different, and there could be come other magic involved)) We implement GEMM on top of BLAS primitives (rocBLAS). WRT iGemm I recommend beginning with googling "What is Implicit Gemm" 😄

**Comment by atamazov** [comment]
@Delta0307 Also please feel free to look into the source code of MIOpen.
