### ISSUE TITLE
[gfx906][SWDEV-366467] ConvAsm1x1U perform significantly differently

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1869]
[10807.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9966278/10807.log)
[11023.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9966279/11023.log)
For the following configuration on gfx906:

> ./bin/MIOpenDriver convfp16 -n 128 -c 512 -H 13 -W 13 -k 1000 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1

We got about **140x perf drop for the same solver**

10807:

MIOpen Backward Data Conv. Algorithm: 1, Solution: 2/ConvAsm1x1U
GPU Kernel Time Backward Data Conv. Elapsed: 1.730399 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv1x1u1, 128, 512, 1, 1, 1000, 13, 13,  22151168000, 132096000, 43264000, 12801, 101, 1.730399
Backward Convolution Data Verifies OK on CPU reference (0.000317889)
 

11023:

MIOpen Backward Data Conv. Algorithm: 1, Solution: 2/ConvAsm1x1U
GPU Kernel Time Backward Data Conv. Elapsed: 244.816223 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv1x1u1, 128, 512, 1, 1, 1000, 13, 13,  22151168000, 132096000, 43264000, 90, 1, 244.816223

**Comment by atamazov** [comment]
In the good log:
```
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, HIP version 5.3.22325, MIOpen version 2.18.0.
...
MIOpen(HIP): Info2 [SetValues] , content inserted: ConvHipImplicitGemmBwdDataV1R1:256,128,64,4,4,2
MIOpen(HIP): Info [GetValues] =ConvAsm1x1U:2,16,4,16,1,2,1,4
MIOpen(HIP): Info2 [Measure] Db::Load time: 42.8843 ms
MIOpen(HIP): Info2 [FindSolutionImpl] Perf Db: record loaded: ConvAsm1x1U
...
GPU Kernel Time Backward Data Conv. Elapsed: 1.730399 ms (average)
```

In 11023 ("bad" log) MIOpen can't find the tuning values for ConvAsm1x1U. The default tuning values provided by the solver heuristics show bad performance:
```
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, HIP version 5.4.22425, MIOpen version 2.19.0.
...
MIOpen(HIP): Info [GetValues] =ConvAsm1x1U:<values not found>
MIOpen(HIP): Info2 [Measure] Db::Load time: 42.1033 ms
MIOpen(HIP): Info [FindSolutionImpl] Perf Db: record not found for: ConvAsm1x1U
MIOpen(HIP): Info [HeuristicInit] !IsValid(): 4,16,8,16,2,2,1,1. Conservative re-init...
MIOpen(HIP): Info [HeuristicInit] 1,4,8,1,1,2,1,1
MIOpen(HIP): Info [GetDefaultPerformanceConfig] 1,4,8,1,1,2,1,1
...
GPU Kernel Time Backward Data Conv. Elapsed: 244.816223 ms (average)
```

The is not a problem per se provided that find-db contains valid information (because we have other faster solvers). However it reports 2.33349 ms (in both logs) for ConvAsm1x1U, which wins.

I think that the root problem is that find-db is out of sync. Missing tuning values for ConvAsm1x1U in perf-db (MIOpen 2.19) seem to be another, less important problem.

**Comment by junliume** [comment]
@atamazov thanks! It does not explain why `ConvAsm1x1U` is so much slower now, right? As an ASM solver, I would expect it not to be impacted by compiler/runtime.

**Comment by DrizztDoUrden** [comment]
As far as I see at the moment, Artem is correct here. There is no entry for the specific solver + config in the perf-db, while there is one in the find-db.
For that reason it gets compiled with very bad perf config and is returned as if it has very good (like the one used for the find-db).

**Comment by junliume** [comment]
Hi @DrizztDoUrden  and @atamazov , yes when I reverted `gfx906_60.db` back to 62d2e1c1bebffb692b1dd7fcf1141150d3bdb473 in this history: https://github.com/ROCmSoftwarePlatform/MIOpen/commits/develop/src/kernels/gfx906_60.db I got good performance again.

However, the **"it gets compiled with very bad perf config"** part puzzles me, what might have caused it?

**Comment by DrizztDoUrden** [comment]
No entry in perf-db and default config is not valid for the problem. A more generic one has been selected.
@Kirpich30000 or @shurale-nkn may enlighten you about the details of why kernel can become 140x slower due to bad perf config, but I have no idea on kernel implementation details. I guess someone may investigate why specific config was so bad, but that may not be worth the time spent. It wouldn't get selected if the dbs were valid.
In general, perf-db should never lack an entry where find-db has one. That would lead to extremely bad results in immediate mode and anything else not evaluating performance.
Maybe we should make a test iterating over the find-db and checking every solver in perf-db. That should be lightning fast.

**Comment by junliume** [comment]
@cderb and @JehandadKhan the critical part is to keep DBs in sync I guess. Could we re-export DBs for gfx906 and check other variations too?

**Comment by atamazov** [comment]
@junliume 
> It does not explain why ConvAsm1x1U is so much slower now, right? 

While this is ASM solver, it still requires tuning to reach optimal performance. And this kernel is very sensitive to the tuning values. In this specific case, tuning info is missing in perf-db and the solver uses its own heuristics to guess tuning values. But that guess ends with tuning values that give very bad performance. Note that there is nothing bad with that provided that find-db is in sync.

We can try to improve the solver's heuristics but I suspect it won't worth efforts.

**Comment by junliume** [comment]
@cderb and @JehandadKhan with `release/rocm-rel-5.4-staging-RC3` this problem is resolved, we can close this issue when the patch is merged into `develop`. Thanks all for the valuable inputs!
