### ISSUE TITLE
[CK] Incorrect logging

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1949]
"Composable kernel" code should not use plain `printf` or similar. Please use MIOPEN_LOG macros or write your own implementation that is:
- thread-safe (logging lines should not be messed up when the application is multithreaded)
- obeys `MIOPEN_LOG_LEVEL_*`, `MIOPEN_ENABLE_LOGGING_MPMT`, `MIOPEN_ENABLE_LOGGING_ELAPSED_TIME`
- obeys the `miopen::debug::LoggingQuiet` flag from logger.hpp
- prints to stderr.

Example of incorrect logging:
```
MIOpen(HIP): Info [FindSolutionImpl] Perf Db: record not found for: ConvHipImplicitGemmFwdXdlops
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmFwdXdlops: Success.
MIOpen(HIP): Info2 [Log] PrecompileKernels Compile Time, ms: 0.749681
launch_and_time_kernel: grid_dim {4056, 1, 1}, block_dim {128, 1, 1}
Warm up 1 time
Start running 10 times...
MIOpen(HIP): Info [EvaluateInvokers] ConvHipImplicitGemmFwdXdlops: : 0.0053118 < 3.40282e+38
MIOpen(HIP): Info2 [Register] Invoker registered for algorithm 192x28x28x3x3x192x26x26x256xNHWCxNHWCxNHWCxFP32x0x0x1x1x1x1x1xF and solver ConvHipImplicitGemmFwdXdlops
```

Where printf came from: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1097/files#r1089546778

**Comment by atamazov** [comment]
[Attribution] @junliume @johnny-keker https://github.com/ROCmSoftwarePlatform/MIOpen/labels/quality https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker, proposed assignees: @asroy @JehandadKhan

**Comment by junliume** [comment]
@illsilin this is a composable kernel related issue and please open corresponding issues in CK's repo. Thanks!

**Comment by atamazov** [comment]
AFAICS the CK related files that contain printf do not reside in CK repo.

**Comment by illsilin** [comment]
Yes, this output comes from the include/ck/host_utility/kernel_launch.hpp.
I agree, it shouldn't be there. I'll clean this up.

**Comment by atamazov** [comment]
@illsilin Do not hesitate to ask for assistance, if necessary.

**Comment by illsilin** [comment]
No problem. I've discussed this with our team and we'll just use the same macro I introduced recently to enable/disable other debugging output that was annoying the ONNX folks.
While I'm at it, I'll also add a macro to turn on/off the warm-up kernel call. We'll leave the warm-up on by default, but the printfs will be all off by default.

**Comment by atamazov** [comment]
@illsilin 
> No problem. I've discussed this with our team and we'll just use the same macro I introduced recently to enable/disable other debugging output that was annoying the ONNX folks.

Does that macro comply the requirements listed at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1949#issue-1560565128?

**Comment by atamazov** [comment]
@illsilin 
> While I'm at it, I'll also add a macro to turn on/off the warm-up kernel call. We'll leave the warm-up on by default, but the printfs will be all off by default.

Can you please explain what is warm-up kernel call in CK (when is it used and what does it do)? I'd like to better understand its side effects (besides logging) for MIOpen.

**Comment by illsilin** [comment]
Well, in this particular case we are simply going to try and avoid that output altogether, since it's not particularly valuable to begin with. Once we get to the point where we really need to dump some debugging info from the kernels on multiple threads for whatever higher-level library, we will come up with some uniform mechanism that will apply to all libraries that consume CK, such as MIOpen, AITemplate, ONNX, etc. We'll make sure that will comply with MIOpen requirements.

The warm-up run is simply the same kernel getting launched once before we launch and time the actual kernels (usually we run the same kernel 10 times and report the average elapsed time). This warm-up helps reduce the kernel launch time.

**Comment by atamazov** [comment]
@illsilin 
> ...we will come up with some uniform mechanism that will apply to all libraries that consume CK, such as MIOpen, AITemplate, ONNX, etc...

~Good. But please note that the problematic code resides in a file that is not a part of CK, it resides in src/composable_kernel/host/host_tensor/include/device.hpp. It seems like this file is a manually tailored copy of include/ck/host_utility/kernel_launch.hpp from CK. So fixing this specific issue in MIOpen looks trivial.~

Update: I am wrong, please ignore this comment.

**Comment by atamazov** [comment]
@illsilin 
> The warm-up run is simply the same kernel getting launched once before we launch and time the actual kernels (usually we run the same kernel 10 times and report the average elapsed time). This warm-up helps reduce the kernel launch time.

MIOpen has to deal with different kinds of kernels, and it is the MIOpen's job to perform warming-up when necessary. So maybe the best solution for us is disabling the warm-up feature of CK. But let's check first -- you may wish to keep warm-up if inaccuracy of timing of CK kernels becomes too high without it.

**Comment by illsilin** [comment]
@atamazov

"MIOpen has to deal with different kinds of kernels, and it is the MIOpen's job to perform warming-up when necessary. So maybe the best solution for us is disabling the warm-up feature of CK. But let's check first -- you may wish to keep warm-up if inaccuracy of timing of CK kernels becomes too high without it."

Yes, as a matter of fact, Microsoft and Meta teams have also requested us to disable warm-up, since their benchmarks have built-in warm-up procedures of their own. So I've set the warm-up flag to 0 as default and ran our standard CI performance tests and it looks like an average performance numbers for gemm kernels only went down by a couple of percent. We can always set it back to 1 during the CI builds, if this becomes an issue.

**Comment by atamazov** [comment]
[Off-topic] @illsilin There is a nifty "quote reply" feature that applies proper formatting at once:
![image](https://user-images.githubusercontent.com/12697412/216176234-326d965b-f588-40ed-9830-bd1e1f854034.png)

**Comment by atamazov** [comment]
@illsilin Agreed, let's go ahead with the fix 👍

**Comment by atamazov** [comment]
@illsilin @asroy Ping

**Comment by ppanchad-amd** [comment]
@illsilin Has this issue been fixed? Thanks!

**Comment by illsilin** [comment]
Yes, I think it's been fixed a long time ago.
