### ISSUE TITLE
5700xt miopenkernel not available. Which should I install?

### ISSUE THREAD

**Issue by Q-Tran** [ROCmSoftwarePlatform/MIOpen#1995]
An appropriate kernel for the 5700xt is not available. upon using the gpu for deep learning I get 
```
Warning [SQLiteBase] Missing system database file: gfx1030_20.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package
```

Looking at the apt repository I do not see a gfx1030_20.kdb I only see a gfx1030_36. Also when reading the documentation on which kernel to use. I see that the correct kernel should be gfx1010_40.kdb. Which kernel should I use?

**Comment by atamazov** [comment]
Ignore this warning. gfx1030/20 based cards are not officially supported and therefore the precompiled binaries (.kdb) are not supplied for your GPU. But this only affects initial runs of neural networks on your system, because MIOpen (1) builds kernels when necessary and (2) supports per-user binary cache for all GPUs.

@junliume This can be closed I think.

**Comment by TerminatorHR** [comment]
@atamazov Is there a way to fix this now? I also have a 5700XT and the same warning.

**Comment by atamazov** [comment]
@TerminatorHR you can safely ignore it. See (1) and (2) from my previous comment.
