### ISSUE TITLE
Using different handles for miopenFindConvolutionForwardAlgorithm and miopenConvolutionForward 

### ISSUE THREAD

**Issue by densamoilov** [ROCmSoftwarePlatform/MIOpen#2082]
The MIOpen documentation says that `miopenFindConvolutionForwardAlgorithm` must be called prior to calling `miopenConvolutionForward` however, it doesn't say that the handle objects used for the calls must be the same. Based on my observations MIOpen uses the handle object to carry over some information between the calls. This means that even if there are two different handle objects that are associated with the same device and stream, and one of them is used for the `miopenFindConvolutionForwardAlgorithm` and another one is used for the `miopenConvolutionForward` call the latter will still fail. 

If my understanding is correct the requirement is a significant discrepancy between MIOpen and cuDNN where `cudnnFindConvolutionForwardAlgorithm` and `cudnnConvolutionForward` can be called using different handles.

Is there a way to circumvent the requirement other than using the immediate API?

**Comment by atamazov** [comment]
@densamoilov Your understanding is correct. We need to update the documentation at least.

Please indicate the importance/urgency of this problem for you (assign labels to this ticket).

Simplified, the reason is that `miopenConvolutionForward` is expecting that all necessary kernels already built, loaded and ready to use, BUT this is not so, because each handle has its own kernel cache.

Do you use different-but-same handle objects from the same thread/process? In other words is MT/MP safety a requirement?

Right away, I can recommend using the Find 2.0 API (see #1503). IIRC It finds an _optimal_ solution just like old Find API (`miopenFindConvolutionForwardAlgorithm`) but returns solver information that is _compatible_ with Immediate Mode API calls. Then you can then use Immediate Mode API to _run_ the found solution. Immediate Mode builds kernels when necessary.

The full interoperability between Find and Immediate Modes is one of our current goals (#374) and I am hoping we already reached a level suitable for you.

@DrizztDoUrden Please confirm my thoughts. Let's discuss this tomorrow.

**Comment by densamoilov** [comment]
Thanks @atamazov, the Find 2.0 API is really helpful. The only thing I'd like to clarify is about interoperability between the modes. The newly introduced `miopenSolution_t` can be queried for workspace size and time but it cannot be queried for a solution ID that is required to call `miopenConvolutionForwardImmediate`. So it doesn't seem like the Find 2.0 API is fully interoperable with the Immediate API.

On the other hand, I tried to call `miopenFindSolutions` with one handle and `miopenRunSolution` with another one (that was associated with the same device but different stream) and I didn't see any issues. Is it expected behavior?

> Please indicate the importance/urgency of this problem for you (assign labels to this ticket).

It seems that I don't have permissions to add labels. We integrated MIOpen in oneDNN and we had to use the Immediate API because of the handle requirement which resulted in suboptimal performance due to picking suboptimal solutions. We want to make sure that we get the best convolution performance from MIOpen.

> Do you use different-but-same handle objects from the same thread/process? In other words is MT/MP safety a requirement?

We have a handle object per thread, all of them within one process are associated with the same device. However, we may set different streams for those handles when we execute an operation.

**Comment by densamoilov** [comment]
One more question about `miopenFindSolutions`. How do I get `maxSolutions` to pass to this function?

**Comment by atamazov** [comment]
@densamoilov 
> `miopenSolution_t` can be queried for workspace size and time but it cannot be queried for a solution ID that is required to call `miopenConvolutionForwardImmediate`. So it doesn't seem like the Find 2.0 API is fully interoperable with the Immediate API.

So far, yes.

> I tried to call miopenFindSolutions with one handle and miopenRunSolution with another one (that was associated with the same device but different stream) and I didn't see any issues. Is it expected behavior?

BTW yes. It seems like 2.0 API can do the job without Immediate Mode calls.

> One more question about `miopenFindSolutions`. How do I get `maxSolutions` to pass to this function?

This is nice question, because we do not say what is the possible max (see [note about `miopenGetSolutionsNumber` for some details](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1503#issue-1192755340)) Recommendations: 

- If you simply need the fastest, use `miopenFindResultsOrderByTime` and ask for 1.
- Use also `miopenSetFindOptionWorkspaceLimit()` if your system might be low on memory.
- If you would like to get all available solutions, and then decide using some specific complex criterion (for example, find a compromise between speed and required workspace), then use reasonably big value, like 1024 or so (here is the [current registry of all available solvers](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/04d3a524f06cc95b1ee6b2771cdc1da667f51a50/src/solver.cpp#L265), and I guess we have ~100 of them).

> It seems that I don't have permissions to add labels. 

Just tell us about the value (unknown/low/middle/high) and urgency (unknown/low/normal/high/critical/blocker), we set the appropriate labels. It would be nice to know even if this problem is already resolved by Find 2.0 API.

CC @junliume @JehandadKhan @DrizztDoUrden

**Comment by densamoilov** [comment]
@atamazov,

> Just tell us about the value (unknown/low/middle/high) and urgency (unknown/low/normal/high/critical/blocker)

I think the value is high as the goal is to get the best performance out of MIOpen. The urgency is normal.

I'm still in the process of testing the API so I don't yet know if it can address the problem completely. While testing the API I got one more question.
The `miopenRunSolution` doesn't seem to support `alpha` and `beta` parameters. Does it mean that the scaling is expected to be executed as separate operations now? If so, what is the motivation for that, given that it will likely hurt performance?

**Comment by DrizztDoUrden** [comment]
> IIRC It finds an optimal solution just like old Find API (miopenFindConvolutionForwardAlgorithm) but returns solver information that is compatible with Immediate Mode API calls.

Technically it is not compatible as there is no API function to extract a solver id from miopenSolution without directly calling the MIOpen internals.

> On the other hand, I tried to call miopenFindSolutions with one handle and miopenRunSolution with another one (that was associated with the same device but different stream) and I didn't see any issues. Is it expected behavior?

Yes, you can even serialize a solution, load it in another process and run it there without calling miopenFindSolution again.

**Comment by densamoilov** [comment]
@atamazov, and one more question. Do you plan to add an algorithm kind query for `miopenSolution_t `? For example, if I want to filter out the FFT algorithm I don't have any tools to do that at this point.

**Comment by atamazov** [comment]
@densamoilov 
> The miopenRunSolution doesn't seem to support alpha and beta parameters. Does it mean that the scaling is expected to be executed as separate operations now? If so, what is the motivation for that, given that it will likely hurt performance?

Well, actually alpha and beta are not supported for convolutions (only fixed values of 1.0 and 0.0 are accepted). So we are not cutting anything in `miopenRunSolution`.

- NB Exception: alpha and beta _are supported_ in miopenConvolutionForwardBias/miopenConvolutionBackwardBias but these primitives are slow and should be considered deprecated.

> Do you plan to add an algorithm kind query for miopenSolution_t ? For example, if I want to filter out the FFT algorithm I don't have any tools to do that at this point.

This is definitely worth to do. For now, if an urgent need arise, please let me know and I'll suggest a workaround.

@DrizztDoUrden Can you add this enhancement into you working queue? I think what we need is:
- Getting `miopenConvSolution_t` from `miopenSolution_t`
- Conversion of `uint64_t solution_id` into `const char* solver_name`, where the solver is the one that produced the solution.

CC @junliume @JehandadKhan 

----
[Attribution] @junliume @johnny-keker
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/enhancement
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_normal
- Proposed assignees:
  - @DrizztDoUrden
  - @atamazov

**Comment by DrizztDoUrden** [comment]
> Conversion of `uint64_t solution_id` into `const char* solver_name`, where the solver is the one that produced the solution.

Right now, users cannot get either of them from `miopenSolution_t`, so the conversion wouldn't achieve much. But it is trivial make getters for either. Original goal was to make a proof-of-concept API with the possibility of future expansion, so it doesn't contain anything not mandatory to do the job.

> Do you plan to add an algorithm kind query for `miopenSolution_t`?

We would need a bit of time to consider this, but technically it is not complicated. `miopenSolution_t` internals have a solver id in them, which can be queried for the algorithm. The problem is that it is supposed to be not locked to convolution. Besides, it may be more practical (that would reduce find time rather than ignore already evaluated solutions) to implement filtering by `miopenFindOptions_t`. Something like algo/solver filtering could be done, but that would also require some consideration and a proper design.

**Comment by densamoilov** [comment]
@atamazov 
>  For now, if an urgent need arise, please let me know and I'll suggest a workaround.

The workaround would really help.

**Comment by DrizztDoUrden** [comment]
@densamoilov I have created a PR, which should resolve the immediate problem. You can try building MIOpen from its branch if you need this ASAP. I hope it will be merged soon though.

**Comment by atamazov** [comment]
@densamoilov I recommend using the code from #2104.

Workaround: you can use the following env var to disable FFT algorithm:
```bash
export MIOPEN_DEBUG_CONV_FFT=0
```
The full list of env variables that can be used for disabling individual solvers and/or algoruithms can be found here: https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/DebugAndLogging.md#filtering-by-algorithm (⚠️ the documentation is a bit outdated).

**Comment by DrizztDoUrden** [comment]
FYI if you want to set an env variable from code, you should do it before any library operations as env var values get cached and are not read again. `MIOPEN_DEBUG_CONV_FFT` is probably only read and cached in convolution-related functions, but I would recommend only using it before the first MIOpen call as caching may change with versions.
In-find filtering would require to get several other PRs merged, so even if I would do it now merging would take a lot of time. So, I would recommend using the branch, env variable or some combination of both as Artem has suggested.

**Comment by densamoilov** [comment]
@DrizztDoUrden, thanks for the clarification.

**Comment by DrizztDoUrden** [comment]
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2104 has been merged into develop.
