### ISSUE TITLE
[QA] auto generate or hand-write?

### ISSUE THREAD

**Issue by muzhailong** [ROCmSoftwarePlatform/MIOpen#2122]
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/f510b9a6a7aeab54fbc98b442710c34a086aa6f7/src/kernels/Conv_Winograd_v21_1_3_gfx9_fp32_f2x3_stride2.inc#LL30C1-L31C1

I want to know wether the code is auto-genetated or hand-written？
This grammar doesn't seem like assembly（for example：.if  .else）, I want to know what grammar it is

Thanks!

**Comment by atamazov** [comment]
@muzhailong 
> I want to know wether the code is auto-genetated or hand-written？

The kernel you're asking about is hand-written. But we use a proprietary assembler due to historical reasons. That proprietary assembly tool can't be included in ROCm. Therefore, the source code is converted from the original source (and may seem "generated").

Does this question have any practical purpose other than curiosity?

> This grammar doesn't seem like assembly（for example：.if .else）, I want to know what grammar it is

Basically, this question should be asked at some other place, but I can answer. The HIP compiler supports assembly language for the AMDGPU targets. The syntax of its directives is very similar to GNU assembler (GAS, or GNU as), see https://sourceware.org/binutils/docs/as/. The syntax of machine instructions can be found at https://llvm.org/docs/AMDGPUUsage.html.

**Comment by muzhailong** [comment]
> @muzhailong
> 
> > I want to know wether the code is auto-genetated or hand-written？
> 
> The kernel you're asking about is hand-written. But we use a proprietary assembler due to historical reasons. That proprietary assembly tool can't be included in ROCm. Therefore, the source code is converted from the original source (and may seem "generated").
> 
> Does this question have any practical purpose other than curiosity?
> 
> > This grammar doesn't seem like assembly（for example：.if .else）, I want to know what grammar it is
> 
> Basically, this question should be asked at some other place, but I can answer. The HIP compiler supports assembly language for the AMDGPU targets. The syntax of its directives is very similar to GNU assembler (GAS, or GNU as), see https://sourceware.org/binutils/docs/as/. The syntax of machine instructions can be found at https://llvm.org/docs/AMDGPUUsage.html.

@atamazov 
Thanks!
`proprietary assembler` mean? could I get and use  it? 

I found many assembly codes were generated by `igemm_codegen.py`, but I couldn't find it, Is this script not publicly available？

**Comment by junliume** [comment]
@muzhailong MISA (iGEMM GEN) repo is here: https://github.com/ROCmSoftwarePlatform/MISA

**Comment by ppanchad-amd** [comment]
@muzhailong Do you still need still assistance with this ticket? If not, please close. Thanks!

**Comment by muzhailong** [comment]
> @muzhailong Do you still need still assistance with this ticket? If not, please close. Th
