### ISSUE TITLE
[Dependency] Latest CK build is taking very long time

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#2248]
if we update CK dependency (this line): https://github.com/ROCmSoftwarePlatform/MIOpen/blob/fd143e601ff760e09a7866c161d8a4289f09376f/requirements.txt#L9
to 
```
ROCmSoftwarePlatform/composable_kernel@4e911f3ee05af375ce6e5757eee6a6435f2293c6 -DGPU_TARGETS="gfx900;gfx906;gfx908;gfx940;gfx90a;gfx1030;gfx1100;gfx1101;gfx1102"
```
the dependency build time increases **very significantly**. 

Even though dependency build is one-time only, CK team needs to take a look at the build profiling. Is it the same issue we have discussed about? i.e. compiler register allocation strategy using eager mode?

**Comment by atamazov** [comment]
Yes, this is compiler issue. Or CK issue at least;)

**Comment by illsilin** [comment]
I think we have a relatively good understanding of what's going on by now.
See the details in the ticket below:
https://ontrack-internal.amd.com/browse/SWDEV-403889
First, the greedy register allocator takes forever to process several int8 instances on all platforms. 
Second, on gfx11 this issue is further aggravated by the failure to vectorize many read and write instructions. 
Thus, current build times for gfx9/gfx10 architectures are around 40 minutes and around 15 hours for the gfx11 architectures.
The compiler team is looking for fixes to both of these.
Once the issues are fixed, the anticipated build times for each architecture are around 10-12 minutes.
In the meantime, I'm working on adding an option to build CK only for select data types. This would allow us not to build int8 instances on gfx11 architectures and avoid the long build times until the greedy register allocator fix is available.

**Comment by illsilin** [comment]
With the latest changes, when we skip building the tests, examples, ckProfiler, int8 and dl instances, CK builds for all gpu targets in about 30 minutes. Once the compiler fix is available, we can also start building int8 instances with no penalty.
