### ISSUE TITLE
Warning message due to file unreadable

### ISSUE THREAD

**Issue by tdsk108** [ROCmSoftwarePlatform/MIOpen#26]
When I ran CaffeNet inference sample after following the installation steps in https://github.com/ROCmSoftwarePlatform/hipCaffe/blob/hip/README.ROCm.md, I observed the following warning message. I obtained the same result with the example on the hipCaffe quick start guide. Could you please let me know if this warning can be ignored?

MIOpen(HIP): Warning [ReadFile] File is unreadable.

It looks the warning is caused by failure in access to /opt/rocm/miopen/share/miopen/db/gfx803_16.cd.pdb.txt which does not exist. There are only following files under /opt/rocm/miopen/share/miopen/db/ in my environment. 
gfx803_64.cd.pdb.txt gfx900_64.cd.pdb.txt

### System configuration
GPU: RX-560
OS: Ubuntu 16.04.3
Package versions: 
 rocm-dkms/rocm-libs 1.7.60
 hip_base 1.4.17494
 hcc 1.1.17493
 miopen-hip 1.2.0-a9949e3
 miopengemm 1.1.5-3c3145b

**Comment by dagamayank** [comment]
@tdsk108 Thanks for the comment. The issue here is that you are running on a GPU for which MIOpen is not optimized for; MIOpen is optimized for 36/64CUs (compute units) for the `gfx803` architecture. However, you are running a 16 CU GPU hence, the warning.

The easiest workaround is that you can copy the `gfx803_64.cd.pdb.txt` file and create a file called `gfx803_16.cd.pdb.txt` in the same location. This will enable decent performance on your GPU.

In the future, we will be tuning MIOpen for a 16 CU GPU as well.

**Comment by tdsk108** [comment]
@dagamayank Thank you. I understand reason of the warning and could remove the warning by the workaround.

**Comment by Ukhupacha** [comment]
Hello there, 
I encountered the same problem but instead of gfx803_**16**.cd.pdx.txt I have  gfx803_**8**.cd.pdx.txt
`MIOpen(HIP): Warning [FindRecordUnsafe] File is unreadable: /opt/rocm/miopen/share/miopen/db/gfx803_8.cd.pdb.txt`

I have a Radeon E9171 MCM  and Fedora 28, and I'm using using the docker rocm/tensorflow. 
Is there a way I can get the gfx803_**8**.cd.pdx.txt file ?

Thanks in advance,
