### ISSUE TITLE
[MI300][APT] pre-compiled kernels package not found.

### ISSUE THREAD

**Issue by danpetreamd** [ROCmSoftwarePlatform/MIOpen#2680]
I've been using the Docker image `rocm/pytorch:rocm6.0_ubuntu20.04_py3.9_pytorch_2.1.1` and I can't find any `apt` pre-compiled kernels package for `MI300`. Is there a pre-compiled kernels package available for MI300?

This is what I found:

```shell
$ apt show miopen-hip-gfx9* | grep Package:
Package: miopen-hip-gfx900kdb
Package: miopen-hip-gfx900kdb6.0.0
Package: miopen-hip-gfx906kdb
Package: miopen-hip-gfx906kdb6.0.0
Package: miopen-hip-gfx908kdb
Package: miopen-hip-gfx908kdb6.0.0
Package: miopen-hip-gfx90akdb
Package: miopen-hip-gfx90akdb6.0.0
```

**Comment by ghost** [comment]
Same here. I would like to install MIOpen for MI300. I would appreciate it if anyone can help this. Thanks

**Comment by sohaibnd** [comment]
Hi @danpetreamd and @ghost, sorry for the late response. The pre-compiled kernels have been recently added to the develop branch (#3319) and should be available in an upcoming release. 

Note that these are **optional** and not required for MIOpen to work. If there is no pre-compiled kernels package installed, MIOpen compiles it once you run the kernel and caches the compiled kernels locally (in $HOME/.cache/miopen by default) so they don’t need to be compiled the next time you run the them. Therefore, the pre-compiled kernels only help reduce the startup latency for **first run** of a neural network and not on subsequent runs ([documentation for reference](https://rocm.docs.amd.com/projects/MIOpen/en/latest/conceptual/cache.html)).

You should also be able to generate the pre-compiled kernels yourself by following the steps [here](https://github.com/ROCm/MIOpen/issues/2955#issuecomment-2394561884), but this will take some time.

**Comment by sohaibnd** [comment]
Closing this issue as it it resolved. Please feel free to re-open it if you are unable to obtain the pre-compiled kernels.

Please note however that pre-compiled kernels will not be included for future architectures as mentioned in other [tickets](https://github.com/ROCm/MIOpen/issues/2740). The pre-compiled kernels are included as a result of having pre-tuned kernel parameter values for the most applicable network configurations so that users can save time by not having to manually tune them for these scenarios ([see docs](https://rocm.docs.amd.com/projects/MIOpen/en/latest/conceptual/perfdb.html)). Now, MIOpen has moved towards using an AI-based heuristic to predict the optimal kernel parameters for a specific configuration (which will work for arbitrary configurations unlike the case with the pre-tuned values). Since the kernel parameters are not known ahead of time and the parameter space is too large, it is not possible to have pre-compiled kernels. While this incurs a slowdown due to having to compile the kernel, this only happens on the 1st run as the compiled kernels get cached (as mentioned above).
