### ISSUE TITLE
Use of HIP `__half` and vector types in MIOpen

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#2726]
Team can we help one of our colaborators by answering the following questions:

* HIP has __half but MIOpen uses _Float16. Do you recommend using _Float16 ?
* To use vector types, do you recommend using ext_vector_type  rather than using HIP’s native vector types?
* Do you have any plans to work on math functions’ compatibility on vector types?

cc @atamazov @junliume

**Comment by dmikushin** [comment]
* `__half` appeared by a need to have it earlier (in ~2016) than `_Float16` got standardized. `_Float16` support is still uneven across compilers, in GCC it is supported only since gcc-12. MIOpen is safe to use `_Float16`, because ROCm is Clang, and Clang got `_Float16` support added quite early. So the choice between the two depends on the target compiler and platform. Likely, GPU/ML world will continue to use `__half`, while `_Float16` will become common in AVX512 CPU code and embedded.
* vector types such as `float4` or `double2` are in fact structs, so they are more portable than any compiler-dependent alternative, but they do not provide any attributes that may help the CPU compiler to vectorize the code.
* In modern GPU architectures, vector types are nothing more than containers, as there are no VLIW or SIMD compute units that can bring any advantage to e.g. `sin` of a float4. Therefore, adding support for vectorized math functions won't bring anything, but syntactic sugar. The only exception is VDPAU.

But all of these questions seem to be more for the HIP devs.

**Comment by atamazov** [comment]
@JehandadKhan I am assuming that the question is about writing the device code. I am unable to quickly find a definite answer to these questions. There are arguments in favor of one solution or another. I strongly recommend asking compiler guys. For now, please look at https://rocm.docs.amd.com/projects/HIP/en/develop/reference/math_api.html.

**Comment by JehandadKhan** [comment]
Summing this up, @kyeonghwanryu I believe we can move forward with the following:

> HIP has __half but MIOpen uses _Float16. Do you recommend using _Float16 ?

Lets stick with `_Float16` since that is the norm in MIOpen, if we decide to move away from, then we can do that in a separate effort.

> To use vector types, do you recommend using ext_vector_type rather than using HIP’s native vector types?

I would agree with @dmikushin  above, structs are indeed more portable.

> Do you have any plans to work on math functions’ compatibility on vector types?

Currently, no.

**Comment by atamazov** [comment]
> Summing this up, @kyeonghwanryu I believe we can move forward with the following:
> 
> > HIP has __half but MIOpen uses _Float16. Do you recommend using _Float16 ?
> 
> Lets stick with `_Float16` since that is the norm in MIOpen, if we decide to move away from, then we can do that in a separate effort.

Please note that existing math intrinsics like __hadd2 or __hfma2 return __half2, see https://rocm.docs.amd.com/projects/HIP/en/develop/reference/math_api.html#hadd2. 

> > To use vector types, do you recommend using ext_vector_type rather than using HIP’s native vector types?
> 
> I would agree with @dmikushin above, structs are indeed more portable.

Unfortunately, this is not so. Vector types have stricter alignment requirements than structs. I think that ext_vector_type ensures proper alignment, but this is only a guess; I think that compiler engineers know the answer.

> > Do you have any plans to work on math functions’ compatibility on vector types?
> 
> Currently, no.

There are some intrinsics already, and it seems logical to add more for BF16 and INT8 types (if ISA has suitable instructions), but only compiler engineers know the exact answer.

Let me talk with compiler guys. I'll be back with more precise answers.
