### ISSUE TITLE
MAX_MEM_ALLOC_SZ limited to 7287183769

### ISSUE THREAD

**Issue by sspencespence** [ROCmSoftwarePlatform/MIOpen#2789]
The hard-coded limit of MAX_MEM_ALLOC_SZ <= 7287183769 in https://github.com/ROCm/MIOpen/blob/release/rocm-rel-5.4/src/solver/gemm.cpp#L203 is detrimental as it limits the applicability of GemmFwdRest solvers. When the workspace size exceeds this limit, the search falls back on the naive direct conv which is much slower.
I can't see from issue #1430 why this limit needs to be hard-coded. Can it be removed? 

E.g. a 3d conv matching the key signature
`32-128-128-128-3x3x3-32-128-128-128-1-1x1x1-1x1x1-1x1x1-0-NCDHW-FP32-F`
on my gfx908 GPU gives 
```
MIOpen(HIP)   0.004: Info [FindConvFwdAlgorithm] FW Chosen Algorithm: GemmFwdRest , 7247757312, 52.4841
```

but small change to 
`33-128-128-128-3x3x3-33-128-128-128-1-1x1x1-1x1x1-1x1x1-0-NCDHW-FP32-F`
gives
```
MIOpen(HIP)   0.017: Info2 [GetWorkspaceSize] 7474249728 > 7287183769
...
MIOpen(HIP)   0.005: Info [FindConvFwdAlgorithm] FW Chosen Algorithm: ConvDirectNaiveConvFwd , 0, 2399.31
```

**Comment by atamazov** [comment]
> I can't see from issue `https://github.com/ROCm/MIOpen/issues/1430` why this limit needs to be hard-coded.

@suspendable This is because issue 1430 mentioned in the source is from some other, old repository.

@junliume Can we partially copy [issue 1430](https://github.com/AMDComputeLibraries/MLOpen/issues/1430) to this repo to shed some more light on the issue? I do not remember all the necessary details. The MAX_MEM_ALLOC_SZ workaround was created by @ce1adon, see https://github.com/ROCm/MIOpen/commit/f8379162bd341d9a59a57f658f42d99129154d01. I suspect that it is no longer needed (thanks to improvements in rocBlas and in pointer math fixes in the library).

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCm/MIOpen/labels/enhancement
- https://github.com/ROCm/MIOpen/labels/performance
- https://github.com/ROCm/MIOpen/labels/urgency_unknown
- https://github.com/ROCm/MIOpen/labels/value_unknown
- Proposed assignees: @atamazov @DrizztDoUrden

**Comment by atamazov** [comment]
@suspendable Please try to run the same convolution with `export MIOPEN_FIND_MODE=1` and let us know the results. There could be some other, more performant, Solvers that can compute this convolution, but they may be hidden due the default Find mode (DYNAMIC_HYBRID).

**_Please also indicate the importance of this problem to you._**

**Comment by ritwickJ** [comment]
Hi,

Thank you for the response. we still see the same naive method being used.

The convolution that we would like to get working looks like this in pytorch
Conv3d(48, 16, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))

MIOpen(HIP)   0.005: Info2 [GetWorkspaceSize] 10871635968 > 7287183769
MIOpen(HIP)   0.004: Info2 [SearchForAllSolutions] GemmFwdRest: Not applicable

MIOpen(HIP)   0.004: Info [ConvolutionForward] algo = 1, workspace = 0
MIOpen(HIP)   0.021: Info2 [GetInvoker] Returning an invoker for problem 48x128x128x128x3x3x3x16x128x128x128x1xNCDHWxFP32x1x1x1x1x1x1x1x1x1x1xF and algorithm miopenConvolutionFwdAlgoDirect

env variables that I set

MIOPEN_ENABLE_LOGGING_ELAPSED_TIME=1
MIOPEN_ENABLE_LOGGING=1
MIOPEN_LOG_LEVEL=6
MIOPEN_FIND_MODE=1

We would say that the importance of this problem is fairly urgent for us. 

Thank you for your help!

**Comment by atamazov** [comment]
@ritwickJ @sspencespence I see. It would be nice if you also zip the console log and attach it to this ticket. Will look into it.

**Comment by sspencespence** [comment]
[conv3d_48_16_128x128x128_3_1_1.log](https://github.com/ROCm/MIOpen/files/14543485/conv3d_48_16_128x128x128_3_1_1.log)

Attached is the debug log from running the convolution ritwickJ mentioned: Conv3d(48, 16, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1)) applied on input data of size 128x128x128, which is typical in our use case.

Thanks for the support!

**Comment by atamazov** [comment]
@ritwickJ @sspencespence I am working on the fix. Preliminary results are promising.

**Comment by atamazov** [comment]
@ritwickJ @sspencespence You are welcome to try this patch (baseline is develop at 70f0225091a64bcd451428ec7107cf609be18426): [fix_issue_2789.diff.txt](https://github.com/ROCm/MIOpen/files/14607501/fix_issue_2789.diff.txt).

I'll prepare a PR now.

**Comment by sspencespence** [comment]
Thanks @atamazov , I'll build and test it and hopefully get back to you early next week :)
Will this branch of MIOpen require ROCm 6, or can I build it with ROCm 5.4.2 ?

**Comment by atamazov** [comment]
@sspencespence 
> Thanks @atamazov , I'll build and test it and hopefully get back to you early next week :) 

Does it work as expected?

> Will this branch of MIOpen require ROCm 6, or can I build it with ROCm 5.4.2 ?

If you can apply it to 5.4.2 without problems, then you can use it, I think. Please let me know if you need more help.

**Comment by atamazov** [comment]
@ritwickJ @sspencespence #2811 had problems and now updated, You're welcome to try new diff:
- For develop [fix_issue_2789_01.diff.txt](https://github.com/ROCm/MIOpen/files/14898138/fix_issue_2789_01.diff.txt)
- For ROCm 5.4.x (conflicts resolved) [fix_issue_2789_01_rocm54.diff.txt](https://github.com/ROCm/MIOpen/files/14898723/fix_issue_2789_01_rocm54.diff.txt)
