### ISSUE TITLE
API to set the MIOPEN_FIND_MODE

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#336]
If we are adding more modes, we need to have a API to control this. This is a requirement for MIGraphX via @pfultz2.

The question is, where will this be tied into? Set to the handle?

**Comment by JehandadKhan** [comment]
I think is a good time for the (very) long await Find 2.0

**Comment by pfultz2** [comment]
We could create an opaque object that has the find settings or use a local struct, but we will need a new API function to pass this along. 

It would also be nice if we can merge `miopenConvAlgoPerf_t` and `miopenConvSolution_t`, but it looks like we screwed that one up(the field for `memory` is called `workspace_size`).

**Comment by JehandadKhan** [comment]
Perhaps the same opaque object may merge immediate and non-immediate as well ?

**Comment by pfultz2** [comment]
> Perhaps the same opaque object may merge immediate and non-immediate as well ?

But that will require adding v2 for immediate mode as well, which then we could switch the name.

**Comment by atamazov** [comment]
Find 2.0 API and Find Modes (and other modes like this) are unrelated so far.

@pfultz2 Would you like to have a global (per library instance) Find Modes or you need capability to specify mode in each call?

**Comment by atamazov** [comment]
> It would also be nice if we can merge `miopenConvAlgoPerf_t` and `miopenConvSolution_t`, but it looks like we screwed that one up(the field for `memory` is called `workspace_size`).

Sure, Replacing `miopenConvAlgoPerf_t` with `miopenConvSolution_t` in Find API 2.0 calls is one of its targets. There is a short survey at https://github.com/AMDComputeLibraries/MLOpen/issues/1938 (100).

**Comment by pfultz2** [comment]
> Find 2.0 API and Find Modes (and other modes like this) are unrelated so far.

Kind of. They are somewhat unrelated but it may be necessary to have a new API function call, and if we are adding a new Find API function call we should make sure it can work with Find 2.0.

> Would you like to have a global (per library instance) Find Modes or you need capability to specify mode for each Find API call?

It would be best to specify it for each API call.

**Comment by daniellowell** [comment]
> > Perhaps the same opaque object may merge immediate and non-immediate as well ?
> 
> But that will require adding v2 for immediate mode as well, which then we could switch the name.

I don't see this as a problem.

**Comment by daniellowell** [comment]
I would like unify the data structures and parameters between find and immediate mode. If this requires V2 of everything that is fine. 

I don't really see a use case for having FIND_MODE toggled for each layer. Is this something that would actually be useful?

**Comment by pfultz2** [comment]
> I would like unify the data structures and parameters between find and immediate mode. If this requires V2 of everything that is fine.

But we could just use a V2 of Find if we reuse the struct for immediate mode.

> I don't really see a use case for having FIND_MODE toggled for each layer. Is this something that would actually be useful?

But I dont see a use case for having per handle either. Its associated with the `Find` call just like `exhaustiveSearch` so it only seems to make sense to be passed to the Find function. 

Also from a user perspective it makes setting the mode local to the find call. A handle could be set up in a completely different part of the code.

**Comment by atamazov** [comment]
> ...Its associated with the Find call just like exhaustiveSearch so it only seems to make sense to be passed to the Find function.

Unfortunately, it is also associated with GWSS calls.

> A handle could be set up in a completely different part of the code.

Yes, but all Find API calls need a handle to be passed. So the user always have handle available.

I see two options:
- (A) Introduce a FindMode object. Extend API with a call to modify the object. Pass it to Find and GWSS calls. 
- (B) Introduce a LibraryOptions object. Extend API with a call to modify it. Store it in the handle.

Variant (A) has a drawback: the updated Find and GWSS calls will be incompatible with current ones. Therefore it should be included into 2.0 API (if we do not want to introduce intermediate version 1.1, which is the case, I believe). So we can't make it very soon.

Variant (B) is like current environment setting, but you can programmatically change it for each call. This is good and bad at the same time. The bad thing is that the user must track its state (or enforce it to known state prior each API call). Good things have the same root:
- The signatures of Find and GWSS calls remain the same.
- The "options" may be used for other purposes, like enforcing auto-tuning, debugging etc.

Another question: opaque handle or transparent struct? The former provides binary code compatibility. If it is required, we have no option. Otherwise I prefer the latter as it easier to implement and extend in the future. Or we can begin with _experimental_ extension with transparent struct (no guarantees to the user), and later implement full-blown opaque thing and release officially.

**Comment by pfultz2** [comment]
> Unfortunately, it is also associated with GWSS calls.

I dont think we need to add it to GWSS. This is max workspace of all solvers, which should always be sufficient to run find with any mode. This also a temporary buffer only for Find. 

Although, I am not against adding a new API for GWSS to support the Find modes, but I think the original API call doesn't need to be deprecated.

> (A) Introduce a FindMode object. Extend API with a call to modify the object. Pass it to Find and GWSS calls.

Well most likely it will be SearchOptions which will include FindMode and `exhaustiveSearch` options as well.

> Therefore it should be included into 2.0 API (if we do not want to introduce intermediate version 1.1, which is the case, I believe). So we can't make it very soon.

We can't break APIs, but I dont see any problem supporting both. I dont see any reason we cant support 2.0 API now. Instead of calling it V2, we could also call it `Advance` since it provides more options.

> Variant (B) is like current environment setting, but you can programmatically change it for each call. This is good and bad at the same time. The bad thing is that the user must track its state (or enforce it to known state prior each API call).

I dont see why we need to sacrifice usability here. 

> opaque handle or transparent struct? The former provides binary code compatibility. 

Well we can break binary compatibility occasionally(as long as we remember to bump the so version). However, an advantage of an opaque object is that the user could just pass `nullptr` to the function to get the default values.

**Comment by atamazov** [comment]
Variant (B) from https://github.com/ROCmSoftwarePlatform/MIOpen/issues/336#issuecomment-658807139 can be used to implement #356

**Comment by pfultz2** [comment]
Here is the API, I suggest:

```cpp
miopenStatus_t miopenCreateSearchOptions(miopenSearchOptions_t* options);
miopenStatus_t miopenDestroySearchOptions(miopenSearchOptions_t options);
// Enable hybrid mode
miopenStatus_t miopenSearchOptionsEnableFindCache(miopenSearchOptions_t options);
// Only use precompiled or assembly kernels
miopenStatus_t miopenSearchOptionsDisableFindCompilation(miopenSearchOptions_t options);
// Enable exhaustive search
miopenStatus_t miopenSearchOptionsEnableExhaustiveSearch(miopenSearchOptions_t options, bool always);

miopenStatus_t miopenFindConvolutionForwardSolution(miopenHandle_t handle,
                                                    const miopenTensorDescriptor_t xDesc,
                                                    const void* x,
                                                    const miopenTensorDescriptor_t wDesc,
                                                    const void* w,
                                                    const miopenConvolutionDescriptor_t convDesc,
                                                    const miopenTensorDescriptor_t yDesc,
                                                    void* y,
                                                    const size_t maxSolutionCount,
                                                    size_t* solutionCount,
                                                    miopenConvSolution_t* solutions,
                                                    void* workSpace,
                                                    size_t workSpaceSize,
                                                    miopenSearchOptions_t options);
```

We could have the search options be passed as `nullptr`, and we can pick a default.

When we set exhaustiveSearch, there is an option to always tune or only when its missing from the DB. 

Then there is settings to control the different search modes. I think this is simpler than having bunch of different find modes. I added `miopenSearchOptionsEnableFindCache` to enable hybrid mode, but if we want to make that the default then it could be called `miopenSearchOptionsDisableFindCache`.

This also can return the solution rather than algorithm, which is why it is named `miopenFindConvolutionForwardSolution` instead of `miopenFindConvolutionForwardAlgorithm` or `miopenFindConvolutionForwardAlgorithmV2`, I think thats much cleaner.

**Comment by JehandadKhan** [comment]
The consensus after the meeting is as follows:

* An additional API that takes as input the handle and the convolution descriptor would set the find mode for the convolution operation associated with the convolution descriptor.
* This API would not be a part of `miopen.h` and would not be supported long term since this is an interim solution and would be  superseded by Find 2.0 
* The rest of API would stay the same.

Please update the comment if I missed something else.

**Comment by pfultz2** [comment]
> An additional API that takes as input the handle and the convolution descriptor would set the find mode for the convolution operation associated with the convolution descriptor.

I dont think it needs the handle.

> The rest of API would stay the same.

We would also update the documentation to say it will be deprecated.

**Comment by JehandadKhan** [comment]
> 
> 
> > An additional API that takes as input the handle and the convolution descriptor would set the find mode for the convolution operation associated with the convolution descriptor.
> 
> I dont think it needs the handle.

Lets wait for @atamazov's analysis and see what he proposes.

> > The rest of API would stay the same.
> 
> We would also update the documentation to say it will be deprecated.

Of course.

**Comment by atamazov** [comment]
Let me try to make some experimental implementation. I will update ticket as soon as have something.

**Comment by atamazov** [comment]
Problem:
- Find Mode needs to know if tuning is enforced. In this case Find Mode is reset to Normal, regardless of the the environment setting.
- In order to find out if tuning is enforced for certain convolution, the library needs to know the direction of convolution. This is because we have [MIOPEN_FIND_ENFORCE_SCOPE](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/perfdatabase.md#miopen_find_enforce_scope).
- Direction is not known when convolution descriptor is being created. Therefore, Find Mode (that should be stored in the convolution descriptor) can't be initialized right away, when convolution descriptor is being created. We can initialize it only during GWSS or Find calls.
- This initialization requires that ConvolutionDescriptor is not `const`. Removing constness would lead to many changes in the library. I think that this is a consequence of, so to say, imperfect design choice to store Find Mode in the inappropriate place. I am going to not allow this choice to cascade through the core of the library like a virus.

I am going to dismiss the [MIOPEN_FIND_ENFORCE_SCOPE](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/perfdatabase.md#miopen_find_enforce_scope) env var and related functionality.

**Comment by JehandadKhan** [comment]
I dont have an objection to the removal of the `MIOPEN_FIND_ENFORCE_SCOPE` since I dont recall ever using it. @daniellowell  do you recall anywhere we use this? 

cc @cderb

**Comment by atamazov** [comment]
@pfultz2 Do you need similar support for FIND_ENFORCE (well... actually it should be renamed to _Search Mode_) stuff right now?

**Comment by atamazov** [comment]
#489
