### ISSUE TITLE
Any plan to hipify Chainer/CuPy ?

### ISSUE THREAD

**Issue by kazulittlefox** [ROCmSoftwarePlatform/MIOpen#4]
Hi.

I'm new to Radeon openComputing/MIOpen, and I'm interested in
RoCm platforms and MIOpen because I usually use AMD graphic cards
in my Home device.

I often use Chainer as a deep-learning backend library, so I want to know 
there is any plan to hipify Chainer and Cupy, as its acceleration library.
And I want to ask what I can do if there has been no plan or it is far from
accomplishing hipify these libraries.

thanks in advance

**Comment by gstoner** [comment]
We have not started any work on Chainer yet.  But love to help you get community developer engangment around Chainer and bring over  HIP/ROCm and MIOpen.


On Jul 5, 2017, at 8:52 PM, kazulittlefox <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi.

I'm new to Radeon openComputing/MIOpen, and I'm interested in
RoCm platforms and MIOpen because I usually use AMD graphic cards
in my Home device.

I often use Chainer as a deep-learning backend library, so I want to know
there is any plan to hipify Chainer and Cupy, as its acceleration library.
And I want to ask what I can do if there has been no plan or it is far from
accomplishing hipify these libraries.

thanks in advance
