### ISSUE TITLE
OpenCL AMD supported/working platforms

### ISSUE THREAD

**Issue by artyom-beilis** [ROCmSoftwarePlatform/MIOpen#62]
Also it is mentioned that ROCm is used as base it isn't clear if:

(a) MiOpen/OpenCL build will work on AMDGPU-PRO drivers or not, would it work on non-Linux platform?
(b) If ROCm is official, should I expect it to work on non-rocm AMD platforms since ROCm has very limited support (only Linux) and only strict HW requirement - PCI-E atomics.

Finally it is more than reasonable to expect MiOpen-OpenCL to work on any major AMD GPU - finally kernel is kernel regardless it runs over ROCm, AMDGPU-PRO or Windows AMD driver

**Comment by dagamayank** [comment]
@artyom-beilis This is more a question about ROCm in general rather than MIOpen. I recommend you bring this up [here](https://github.com/RadeonOpenCompute/ROCm).

You can browse this page about supported hw and sw.
https://rocm.github.io/ROCmInstall.html#hardware-support
https://rocm.github.io/ROCmInstall.html#software-support

/cc @jlgreathouse

**Comment by jlgreathouse** [comment]
Hi @artyom-beilis 

My understanding is that ROCm is required for MIOpen, even when using OpenCL kernels, primarily because the kernels depend on our LLVM-based OpenCL compiler (which is sometimes referred to as Lightning Compiler). This compiler stack takes OpenCL code and translates it directly to GCN through LLVM IR instead of using an other intermediate language like HSAIL.

This is important because the kernels in MIOpenGEMM (which serve as the basis for MIOpen's OpenCL path) use:
- Inline assembly and LLVM builtins within some of the kernels, which require compiler extensions not supported in our proprietary or HSAIL-path compilers.
- Raw assembly kernels, which are compiled to the ROCm code object format.

The former can likely be used with other software stacks (such as amdgpu-pro and Windows) assuming those teams enable LLVM-IR based compilation through our Lightning Compiler. I don't have any information about whether those teams plan to do this. At one point in time, the amdgpu-pro team shipped a working ROCm user-land code with their release, but I don't know if they still do or plan to in the future. I personally have even less information about whether any of the Windows driver teams plan to do this.

The latter point means that, for now, even if our OpenCL kernels worked on other software stacks, you likely would not get maximum performance. We use our hand-rolled assembly kernels to squeeze as much performance out of our hardware as possible.

Your requests are perfectly reasonable, and we've heard them. We would like to enable all AMD customers to take advantage of the great work that's been going on in the MIOpen project. That said, we're currently focusing our efforts on the ROCm software stack because it let's us rapidly iterate on all parts of the software stack to help achieve the performance we want to deliver.

**Comment by artyom-beilis** [comment]
Thank you for the detailed answer.

This makes MIOpen hugely limited and hampered in comparison even to cuDNN.

It does not only limits users to specific platform (Linux) but also to a very limited set of hardware such that even latest and up-to date one would fail to work

https://github.com/RadeonOpenCompute/ROCm/issues/608
https://github.com/RadeonOpenCompute/ROCm/issues/594


- No Windows
- No quite capable APU (i.e. 1.5 TFlops is more than enough for medium DL tasks)
- no eGPU
- no generic PCI Express. 

Thanks for clarifications and huge disappointment, as I understand miOpen/ROCm/HIP stack is far from being ready for prime time.

**Comment by jlgreathouse** [comment]
Thank you for the detailed feedback.
