### ISSUE TITLE
[NHWC] Disable GEMM for non-NCHW layouts

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#744]
Let's disable it until support for NHWC layout is ready in Gemm Solvers. This can be done quickly. Originated from:
- https://github.com/ROCmSoftwarePlatform/MIOpen/pull/728#issuecomment-776729433
- https://github.com/ROCmSoftwarePlatform/MIOpen/issues/742#issuecomment-777585900

As reworking of existing GEMM into Solvers is ongoing, I am assigning also @DrizztDoUrden.

**Comment by ce1adon** [comment]
Add @jerryyin as the watcher

**Comment by atamazov** [comment]
@ce1adon There is no "watchers" in github. We can simply add as an assignee. BTW do you have enough rights for that?

**Comment by jerryyin** [comment]
@ce1adon also agreed to take at least part of this issue. I hope between @ce1adon and @DrizztDoUrden and clarify the owner.

In the short term, I'd be fine with either:
- Using the environment variable, if everything else can be guaranteed to give right result
- Disable gemm, this will result in a lot of if/else conditions

In the long term, given that gemm is both consuming a lot of memory as well as slow, we might want to give following alternatives a try:
- Make gemm to a regular solver, instead of an built-in catch all option
- Implement only 1x1 solvers, where execution and memory consumption are reasonable
- Implement everything. There's going to be a lot of work for very little gain.

**Comment by atamazov** [comment]
Yes, right now @DrizztDoUrden is reworking the whole GEMM to Solvers/Invokers. Forward Gemm is almost ready, see #473. So I agree with you WRT options 1/2.

**Comment by ce1adon** [comment]
@jerryyin @atamazov 
By reviewing the current code, I realize the GEMM paths (including the getWorkSpaceSizeGEMM) have already wrapped by the evn var MIOPEN_USE_GEMM. You can simply turn off the env var to disable GEMM's usage of workspace in NHWC mode. If there are still errors, it must come from other things.

**Comment by atamazov** [comment]
Yes. This issue is not a showstopper for reference NHWC solvers/kernels.

However, you won't be able to gradually add NHWC support to GEMM without resolving this issue first. Under "gradually" I mean implementing NHWC for Forward in one PR, then for Backward Data in other PR etc. Because, if you implement NHWC for Forward and enable GEMM you'll immediately get errors for Backward and WrW.

**Comment by jerryyin** [comment]
Will make the environment variable to disable gemm as default, in June demo. Confirmed that this won't be a blocking issue.

**Comment by DrizztDoUrden** [comment]
Should I check all the tensors for being NCHW or only one?

**Comment by atamazov** [comment]
Yes. We have `IsLayoutDefault()` in old ProblemDescription.

**Comment by carlushuang** [comment]
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/765 this PR support NHWC in conv_2d/3d ctest driver. And currently I must use `export MIOPEN_DEBUG_CONV_GEMM=0` before running any ctest, otherwise it will ctest will choose gemm algorithm and have fail result

**Comment by DrizztDoUrden** [comment]
Done for forward, other directions in still progress with the solvers+invokers. Would make bwd data PR soon, WrW would follow.

**Comment by atamazov** [comment]
via #800, #852
