### ISSUE TITLE
In practical use, we should first ensure the completion of the task

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#835]
![image](https://user-images.githubusercontent.com/63989327/112943095-9dca4200-9163-11eb-979c-6bbd46774737.png)
This task with search on has been running for a week, and then, there is some errors occured. According to the message and source code, we can know the last error happened in `hip_build_utils.cpp:HipBuildImpl` function while compiling kernel with default solution. Before this error, there is some kernels available and are able to complete the task, but miopen doesn't catch the exception. It's annoying to see that after weeks running. I'd rather MIOpen output error logs to help me determine if I need to run again, rather than stop directly.
I think we should first ensure the completion of the task, it's user-friendly. I checked the source code, there is no effective means to ensure that.

**Comment by atamazov** [comment]
@zpwenjh 
> This task with search on has been running for a week...

Please describe the process, and I'll try to advise how to accelerate this. Am I right that you've tried `MIOPEN_FIND_ENFORCE=4`?

> ...there is some errors occurred. 

Due to too many files open, right?

**Comment by atamazov** [comment]
@zpwenjh Ping --
> Please describe the process, and I'll try to advise how to accelerate this.

**Comment by zpwenjh** [comment]
> @zpwenjh
> 
> > This task with search on has been running for a week...
> 
> Please describe the process, and I'll try to advise how to accelerate this. Am I right that you've tried `MIOPEN_FIND_ENFORCE=4`?
> 
> > ...there is some errors occurred.
> 
> Due to too many files open, right?

@atamazov Yes, I am using `MIOPEN_FIND_ENFORCE=4`, but the error messege is not same as "too many open files". At first, I thought there was not enough hard disk space, but it's not this situation.

**Comment by atamazov** [comment]
> > @zpwenjh
> > > This task with search on has been running for a week...

I suspect that the reason is that `MIOPEN_FIND_ENFORCE=4` ___always___ performs tuning. Even if some config has been tuned 5 minutes ago. Therefore I recommend using `MIOPEN_FIND_ENFORCE=3`. In this mode, the tuning will be performed only once. 

However, as you can see [in the doc](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/perfdatabase.md#miopen_find_enforce),
> _If optimized values already reside in PerfDb, then auto-tune will not be performed._

This means that values that reside in the System perf-db will block tuning. In order to avoid that, you need to disable the System perf-db somehow before launching your task. This can be done by `export MIOPEN_SYSTEM_DB_PATH=/dev/null` or something alike.

The unwanted side effects are that, along with the System perf-db, both the _System find-db_ and _precompiled kernels_ will not be read by the library. However, this is not very important because:
- The library enforces the Normal Find mode when you use `MIOPEN_FIND_ENFORCE`, and the presence of find-db does not matter in this case.
- The performance gain that can be provided by precompiled kernels during tuning is negligible.
 
As a positive side effect, this may resolve the issue with "too many open files".

Please let me know if this helps.
