### ISSUE TITLE
Codecov is useless and harmful

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#853]
_It's sad to say, but_ -- Reports are useless because information is usually incorrect.

Harmful as useless info is cluttering our PRs and hinders reviewing 
<details><summary>(Example)</summary>

![image](https://user-images.githubusercontent.com/12697412/114203901-45fcb980-9961-11eb-8d74-a09677440314.png)
</details>

**Comment by pfultz2** [comment]
> Harmful as useless info is cluttering our PRs and hinders reviewing

How is that info useless in the image you posted? Why aren't we adding unit tests for these solvers?

**Comment by pfultz2** [comment]
We definitely should not disable it just because it might seem annoying to those that are choosing not to add unit tests for code they are adding/modifying.

**Comment by atamazov** [comment]
> How is that info useless in the image you posted? Why aren't we adding unit tests for these solvers?

We test is with -DMIOPEN_USE_MLIR=On.

**Comment by atamazov** [comment]
Unit test for individual Solvers seem useless. For example, how do the unit test find out if `IsApplicable()` returns correct result? Or if WorkspaceSize returns correct value? Generally, the test needs to `GetSolution()`, build the necessary kernels and veriy the result. Something simpler boils down to testing against literal constants, which don't really test anything and does not worth the time and efforts. That is why we test Solvers at Integration/System level.

**Comment by pfultz2** [comment]
> Unit test for individual Solvers seem useless.

They are not. Unit tests will ensure the solvers do the what developers expect. This can avoid adding code like [this](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/490/files#diff-9e8bfb8df48f491e73a98e9a832971bdfdb3d89f06defb907ccad5588ff0dcfaL295) to the solvers, which the developer most likely expected it to do something but it didn't actually do anything. 

> For example, how do the unit test find out if IsApplicable() returns correct result? Or if WorkspaceSize returns correct value?

There is more than just `IsApplicable()` or workspace size. There is also `GetSolution()` and the performance config validation.

> Generally, the test needs to GetSolution(), build the necessary kernels and veriy the result.

But that is not a unit test. A unit test should be thorough, fast, isolated, consistently repeatable, and as simple as possible. Besides not being fast nor isolated, the proposed testing is not thorough(unless you intend to verify many different tuning configurations). 

> Something simpler boils down to testing against literal constants, which don't really test anything and does not worth the time and efforts.

This is not true. Such tests help ensure the solver works as the developer expected. For example, if the developer knows that a certain combinations of tuning configurations produce incorrect results, then they may exclude it in the `IsValid` method. However, if this has bug in it and such configurations are not excluded, then verification would only catch such bug if we verify all tuning configs(which we dont) or it happens to be picked as the fastest configuration.

> That is why we test Solvers at Integration/System level.

Having unit tests doesn't negate the need for system level testing, and vice-versa because a developer's expectation is not a subset of correctness. System-level testing could show correct results while still not doing what the developer expected. 

Both level of testing is needed, and coverage reports is a great tool to help improve unit testing. Whether or not you agree, doesn't mean we should remove coverage reports which may useful to other developers that do want to unit test their code.

**Comment by atamazov** [comment]
> A unit test should be thorough, fast, isolated, consistently repeatable, and as simple as possible. 

It is quite possible that I simply not smart enough to understand what do you mean. So I would be grateful if you show this in practice, -- take the simplest Solver and write a proper (thorough, fast, isolated etc) unit test for it.

> Whether or not you agree...

Well, actually I do not care much, but it sounds like "your opinion does not matter".
