### ISSUE TITLE
[Recommendation] `ConvHipImplicitGemmMlirBinFwd` -> `ConvMlirImplicitGemmBinFwd` and ditto all other MLIR solvers.

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#869]
[Recommendation] `ConvHipImplicitGemmMlirBinFwd` -> `ConvMlirImplicitGemmBinFwd` and ditto `MIOPEN_DEBUG_CONV_HIP_IMPLICIT_GEMM_MLIR_BIN_FWD`. Why: "Hip" here means that the kernels are (mostly, at least) written in HIP language. This one uses generated MLIR as a source. That fact that MLIR is based on the same llvm compiler as HIP (which is actually not so yet ;) does not matter in this specific case.

If you decide to follow this, I recommend making a separate PR.

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/841#discussion_r615302923_

**Comment by jerryyin** [comment]
@atamazov Could we adopt the following simplify the name such that:
 - we drop `Bin` because it is going to be the only backend in MIOpen
 - Make `ImplicitGemm` into `Igemm` to shorten the spelling

The results naming below for non-xdlops solver:
 - ConvMlirIgemmFwd
 - ConvMlirIgemmBwd
 - ConvMlirIgemmWrW

For xdlops solver:
 - ConvMlirIgemmFwdXdlops
 - ConvMlirIgemmBwdXdlops
 - ConvMlirIgemmWrWXdlops

**Comment by atamazov** [comment]
No objections.

**Comment by jerryyin** [comment]
For documentation purpose, the updated filename will be:

non-xdlops solvers:
  - solver/conv_mlir_igemm_fwd.cpp
  - solver/conv_mlir_igemm_bwd.cpp
  - solver/conv_mlir_igemm_wrw.cpp

xdlops solvers:
  - solver/conv_mlir_igemm_fwd_xdlops.cpp
  - solver/conv_mlir_igemm_bwd_xdlops.cpp
  - solver/conv_mlir_igemm_wrw_xdlops.cpp

**Comment by atamazov** [comment]
via #896
