### ISSUE TITLE
Error: Too many open files

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#962]
I'm runing mask_rcnn with miopen-2.8 in gfx906, rocm ver is 3.9.1, and I get errors as follows:
![image](https://user-images.githubusercontent.com/63989327/120444419-2e1e4080-c3ba-11eb-9a36-3e40b39d49f2.png)
Then I run the script again, the log is here:
[log_miopenerror.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6583045/log_miopenerror.zip)

**Comment by junliume** [comment]
@zpwenjh Issue might be temporarily bypassed by increasing the OS limit on # of open files:
https://github.com/lynckia/licode/issues/102#issuecomment-41947660
https://www.tecmint.com/increase-set-open-file-limits-in-linux/

However, @atamazov could you please take a look why are we opening so many files without closing them?

**Comment by junliume** [comment]
Hi @atamazov  could this be another side effect of #858 and fixed again by #963?

@zpwenjh have you tried the work around and/or later version of MIOpen? If the issue is no longer observed, please close this issue. Thanks!

**Comment by zpwenjh** [comment]
@junliume I have tried MIOpen-2.11.0 too, but the problems still remains.

**Comment by atamazov** [comment]
> could this be another side effect of #858 and fixed again by #963?

No. That changes only affect MIOpen build process.

**Comment by zpwenjh** [comment]
@atamazov 
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/81c0e4f98a548710626b75ef324774a174a80f0e/src/hipoc/hipoc_program.cpp#L167-L174
What's MIOPEN_WORKAROUND_SWDEV_225285? If I can use `hipModuleLoadData` then this problem can be solved.

**Comment by junliume** [comment]
> 225285

HIP claims to have fixed 225285 by https://github.com/ROCm-Developer-Tools/HIP/pull/1988 previously the workaround is to write the hsa object to a temporary file and use hipModuleLoad instead of hipModuleLoadData.

@JehandadKhan if issues in 225285 have been fixed, can we remove the workaround?

**Comment by JehandadKhan** [comment]
Please run mask RCNN by setting `MIOPEN_FIND_MODE=5` environment variable.

**Comment by atamazov** [comment]
> @JehandadKhan if issues in 225285 have been fixed, can we remove the workaround?

This was fixed in ROCm 3.4 and I have been planning to remove it for a long time, but there was always no time. I will make a patch soon.

**Comment by atamazov** [comment]
@zpwenjh Can you please confirm that #981 fixes this issue? Thanks!

**Comment by atamazov** [comment]
#981 merged.

**Comment by atamazov** [comment]
> @zpwenjh Can you please confirm that #981 fixes this issue? Thanks!

**Comment by zpwenjh** [comment]
> @zpwenjh Can you please confirm that #981 fixes this issue? Thanks!

Sorry, I'm late. #981 have fixed this issue if I used miopen with comgr.

**Comment by atamazov** [comment]
@zpwenjh thanks.

**Comment by atamazov** [comment]
@zpwenjh 

## Reason of the issue

Currently MIOpen uses hipModuleLoad to load programs onto GPU. In this case HIP runtime holds a file descriptor per each HIP Program object. "Too many open files" means that the application uses a lot of HIP Program objects, so the limit of open files has been exceeded. Usually this limit is 1024.

## Workaround

I recommend using something like  `ulimit -Sn 2048` or (something else, as [suggested above by @junliume](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/962#issuecomment-853549662)) to increase the limit instead of COMGR.

Why: We use `hipModuleLoadData` in a way that violates HIP runtime restrictions (see #1359). Therefore we are going to revert #981 soon, as a workaround for the problem.
